"For You":
  Home:
    keys: [KEY_LEFT]

  Live:
    keys: [KEY_RIGHT]

  Apps:
    keys: [KEY_RIGHT, KEY_RIGHT]

  Sony LIV:
    keys: [KEY_RIGHT, KEY_RIGHT, KEY_DOWN, KEY_DOWN]

  Search:
    keys: [KEY_LEFT, KEY_UP]

  Search Input:
    keys: [KEY_LEFT, KEY_UP, KEY_ENTER, KEY_UP]

  Settings:
    keys: [KEY_LEFT, KEY_DOWN, KEY_DOWN]

  App Settings:
    keys:
      [
        KEY_RIGHT,
        KEY_RIGHT,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
      ]
  App Settings:
    keys:
      [
        KEY_RIGHT,
        KEY_RIGHT,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
      ]

"Live":
  For You:
    keys: [KEY_LEFT]

  Apps:
    keys: [KEY_RIGHT]

  Sony LIV:
    keys: [KEY_RIGHT, KEY_DOWN, KEY_DOWN]

  Search:
    keys: [KEY_LEFT, KEY_LEFT, KEY_UP]

  Search Input:
    keys: [KEY_LEFT, KEY_LEFT, KEY_ENTER, KEY_UP, KEY_UP]

  Settings:
    keys: [KEY_LEFT, KEY_LEFT, KEY_DOWN, KEY_DOWN]

"Apps":
  For You:
    keys: [KEY_LEFT, KEY_LEFT]

  Live:
    keys: [KEY_LEFT]

  Sony LIV:
    keys: [KEY_DOWN, KEY_DOWN]

  Search:
    keys: [KEY_LEFT, KEY_LEFT, KEY_LEFT, KEY_UP]

  Search Input:
    keys: [KEY_LEFT, KEY_LEFT, KEY_LEFT, KEY_UP, KEY_ENTER, KEY_UP]

  Settings:
    keys: [KEY_LEFT, KEY_LEFT, KEY_LEFT, KEY_DOWN, KEY_DOWN]

  App Settings:
    keys:
      [
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
        KEY_DOWN,
      ] 

"Home":
  Search:
    keys: [KEY_UP]

  Sony LIV:
    keys: [KEY_RIGHT, KEY_RIGHT, KEY_RIGHT, KEY_DOWN, KEY_DOWN]

  Connected Devices:
    keys: [KEY_DOWN]

  Settings:
    keys: [KEY_DOWN, KEY_DOWN]

  Privacy Choices:
    keys: [KEY_DOWN, KEY_DOWN, KEY_DOWN]

  Search Input:
    keys: [KEY_UP, KEY_ENTER, KEY_UP]

"Search Screen":
  Search Input:
    keys: [KEY_UP]

"Search Input":
  Sony LIV App:
    keys: [KEY_DOWN, KEY_DOWN]

"Sony LIV App Installation Screen":
  Install:
    keys: [KEY_DOWN]

"Recently Viewed":
  Search Input:
    keys: [KEY_UP]

"Downloaded App":
  Sony LIV:
    keys: [KEY_DOWN, KEY_DOWN]

"Settings":
  Profile:
    keys: [KEY_UP, KEY_UP, KEY_UP, KEY_UP]
    keys: [KEY_UP, KEY_UP, KEY_UP, KEY_UP]

  Search:
    keys: [KEY_UP, KEY_UP, KEY_UP]

  Home:
    keys: [KEY_UP, KEY_UP, KEY_RIGHT]

  Sony LIV:
    keys: [KEY_UP, KEY_UP, KEY_RIGHT, KEY_RIGHT, KEY_RIGHT, KEY_DOWN, KEY_DOWN]

"Sony LIV":
  Apps:
    keys: [KEY_UP, KEY_UP]

"App Settings":
  Sony LIV Delete:
    keys: [KEY_DOWN, KEY_DOWN]

  Sony LIV ATH:
    keys: [KEY_DOWN, KEY_DOWN]
  
  Sony LIV Lock:
    keys: [KEY_DOWN, KEY_DOWN, KEY_DOWN]
  
"Delete":
  Delete:
    keys: [KEY_LEFT]

"Sony LIV Home":
  Sony LIV Search:
    keys: [KEY_DOWN, KEY_LEFT]
  Movies:
    keys: [KEY_DOWN, KEY_DOWN, KEY_DOWN, KEY_DOWN, KEY_DOWN, KEY_DOWN]

"Sony LIV Search":
  Search Banner:
    keys: [KEY_RIGHT]

"Search":
  Search Input:
    keys: [KEY_UP]

"Sony LIV Movies":
  Movie:
    keys: [KEY_LEFT, KEY_LEFT, KEY_LEFT, KEY_RIGHT]     